//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Staff.Application.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SAVE_SUCCESS", resourceCulture);
            }
        }
        
        internal static string SAVE_FAILD {
            get {
                return ResourceManager.GetString("SAVE_FAILD", resourceCulture);
            }
        }
        
        internal static string DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        internal static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        internal static string UPDATE_FAILED {
            get {
                return ResourceManager.GetString("UPDATE_FAILED", resourceCulture);
            }
        }
        
        internal static string DELETE_FAILED {
            get {
                return ResourceManager.GetString("DELETE_FAILED", resourceCulture);
            }
        }
        
        internal static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        internal static string INVALID_ORGANIZATION {
            get {
                return ResourceManager.GetString("INVALID_ORGANIZATION", resourceCulture);
            }
        }
        
        internal static string INVALID_DEPARTMENT {
            get {
                return ResourceManager.GetString("INVALID_DEPARTMENT", resourceCulture);
            }
        }
        
        internal static string DESIGNATION_EXISTS {
            get {
                return ResourceManager.GetString("DESIGNATION_EXISTS", resourceCulture);
            }
        }
        
        internal static string DEPARTMENT_EXISTS {
            get {
                return ResourceManager.GetString("DEPARTMENT_EXISTS", resourceCulture);
            }
        }
        
        internal static string INVALID_DESIGNATION {
            get {
                return ResourceManager.GetString("INVALID_DESIGNATION", resourceCulture);
            }
        }
        
        internal static string AGE_MINIMUM {
            get {
                return ResourceManager.GetString("AGE_MINIMUM", resourceCulture);
            }
        }
        
        internal static string AGE_MAXIMUM {
            get {
                return ResourceManager.GetString("AGE_MAXIMUM", resourceCulture);
            }
        }
        
        internal static string INVALID_STAFF {
            get {
                return ResourceManager.GetString("INVALID_STAFF", resourceCulture);
            }
        }
        
        internal static string SAME_STAFF_USAGE_FOR_REVIEWER {
            get {
                return ResourceManager.GetString("SAME_STAFF_USAGE_FOR_REVIEWER", resourceCulture);
            }
        }
        
        internal static string INVALID_REVIEW {
            get {
                return ResourceManager.GetString("INVALID_REVIEW", resourceCulture);
            }
        }
        
        internal static string CHECK_IN_SUCCESS {
            get {
                return ResourceManager.GetString("CHECK_IN_SUCCESS", resourceCulture);
            }
        }
        
        internal static string CHECK_OUT_SUCCESS {
            get {
                return ResourceManager.GetString("CHECK_OUT_SUCCESS", resourceCulture);
            }
        }
        
        internal static string CHECK_IN_FAILED {
            get {
                return ResourceManager.GetString("CHECK_IN_FAILED", resourceCulture);
            }
        }
        
        internal static string CHECK_OUT_FAILED {
            get {
                return ResourceManager.GetString("CHECK_OUT_FAILED", resourceCulture);
            }
        }
        
        internal static string ALREADY_CHECKED_IN {
            get {
                return ResourceManager.GetString("ALREADY_CHECKED_IN", resourceCulture);
            }
        }
        
        internal static string ALREADY_CHECKED_OUT {
            get {
                return ResourceManager.GetString("ALREADY_CHECKED_OUT", resourceCulture);
            }
        }
        
        internal static string CHECK_IN_REQUIRED {
            get {
                return ResourceManager.GetString("CHECK_IN_REQUIRED", resourceCulture);
            }
        }
        
        internal static string INVALID_ATTENDANCE {
            get {
                return ResourceManager.GetString("INVALID_ATTENDANCE", resourceCulture);
            }
        }
        
        internal static string INVALID_CHECK_IN_TIME {
            get {
                return ResourceManager.GetString("INVALID_CHECK_IN_TIME", resourceCulture);
            }
        }
        
        internal static string INVALID_CHECKI_IN_CHECK_OUT_TIME {
            get {
                return ResourceManager.GetString("INVALID_CHECKI_IN_CHECK_OUT_TIME", resourceCulture);
            }
        }
        
        internal static string LEAVE_TYPE_EXISTS {
            get {
                return ResourceManager.GetString("LEAVE_TYPE_EXISTS", resourceCulture);
            }
        }
    }
}
